services:
  - type: web
    name: house-booking
    plan: free
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: postgres  # Use the existing PostgreSQL database provisioned on Render
          property: connectionString

  - type: redis
    name: redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: noeviction
    envVars:
      - key: REDIS_URL
        fromDatabase:
          name: postgres  # Use the same PostgreSQL database for Redis
          property: redisURL
